name: sophius
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - numpy
  - bitmath
  - ipykernel
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.6
  - notebook
  - matplotlib
  - pytest



